version: '3'
services:
  fork:
    image: aztecprotocol/foundry:25f24e677a6a32a62512ad4f561995589ac2c7dc-${ARCH_TAG:-amd64}
    pull_policy: always
    entrypoint: 'anvil --silent -p 8545 --host 0.0.0.0 --chain-id 31337'
    ports:
      - 8545:8545

  sandbox:
    image: aztecprotocol/aztec:${AZTEC_DOCKER_TAG:-latest}
    command: 'start --sandbox'
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-verbose}
      ETHEREUM_HOST: http://fork:8545
      L1_CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL_MS: 50
      P2P_BLOCK_CHECK_INTERVAL_MS: 50
      SEQ_TX_POLLING_INTERVAL_MS: 50
      WS_BLOCK_CHECK_INTERVAL_MS: 50
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
      HARDWARE_CONCURRENCY: ${HARDWARE_CONCURRENCY:-}
    expose:
      - '8080'

  end-to-end:
    image: aztecprotocol/end-to-end:${AZTEC_DOCKER_TAG:-latest}
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-verbose}
      ETHEREUM_HOST: http://fork:8545
      L1_CHAIN_ID: 31337
      PXE_URL: http://sandbox:8080
    working_dir: /usr/src/yarn-project/cli-wallet/test
    entrypoint: >
      sh -c '
        while ! nc -z sandbox 8080; do sleep 1; done;
        ./test.sh
      '
    volumes:
      - ../log:/usr/src/yarn-project/end-to-end/log:rw
    depends_on:
      - sandbox
      - fork
