[package]
name = "noir_aztec"
authors = ["aztec-labs"]
compiler_version = ">=0.18.0"
type = "lib"

[dependencies]
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages", tag="v0.82.3-nightly.20250401", directory="noir-projects/noir-protocol-circuits/crates/types" }
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" }
