[package]
name = "schnorr_single_key_account_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
authwit = { path = "../../../../aztec-nr/authwit" }
schnorr = { tag = "v0.1.3", git = "https://github.com/noir-lang/schnorr" }
