[package]
name = "types"
type = "lib"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
sha256 = { tag = "tf/unconstrained-optimized-version", git = "https://github.com/noir-lang/sha256" }
