services:
  ethereum:
    image: aztecprotocol/foundry:25f24e677a6a32a62512ad4f561995589ac2c7dc-${ARCH_TAG:-amd64}
    entrypoint: >
      sh -c '
      if [ -n "$$FORK_BLOCK_NUMBER" ] && [ -n "$$FORK_URL" ]; then
        exec anvil --silent -p "$$ANVIL_PORT" --host 0.0.0.0 --chain-id 31337 --fork-url "$$FORK_URL" --fork-block-number "$$FORK_BLOCK_NUMBER"
      else
        exec anvil --silent -p "$$ANVIL_PORT" --host 0.0.0.0 --chain-id 31337
      fi'
    ports:
      - "${ANVIL_PORT:-8545}:${ANVIL_PORT:-8545}"
    environment:
      FORK_URL:
      FORK_BLOCK_NUMBER:
      ANVIL_PORT: ${ANVIL_PORT:-8545}

  # TODO: add a readiness probe to this
  # TODO: delete all of these extra images and just have one, then symlink them???
  blob-sink:
    image: aztecprotocol/blob-sink
    ports:
      - "${BLOB_SINK_PORT:-5052}:${BLOB_SINK_PORT:-5052}"

  aztec:
    image: "aztecprotocol/aztec"
    ports:
      - "${PXE_PORT:-8080}:${PXE_PORT:-8080}"
    environment:
      LOG_LEVEL: # Loaded from the user shell if explicitly set
      HOST_WORKDIR: "${PWD}" # Loaded from the user shell to show log files absolute path in host
      ETHEREUM_HOST: ${ETHEREUM_HOST:-http://ethereum}:${ANVIL_PORT:-8545}
      L1_CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL_MS: 50
      P2P_BLOCK_CHECK_INTERVAL_MS: 50
      SEQ_TX_POLLING_INTERVAL_MS: 50
      WS_BLOCK_CHECK_INTERVAL_MS: 50
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
      SEQ_BLOB_SINK_URL: http://blob-sink:${BLOB_SINK_PORT:-5052}
      PXE_PORT: ${PXE_PORT:-8080}
      PORT: ${AZTEC_NODE_PORT:-8080}
      TEST_ACCOUNTS: ${TEST_ACCOUNTS:-true}
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log:rw
    depends_on:
      - ethereum
      - blob-sink
    command: "start --sandbox"
