[package]
name = "simple_token_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
uint_note = { path = "../../../../aztec-nr/uint-note" }
compressed_string = { path = "../../../../aztec-nr/compressed-string" }
authwit = { path = "../../../../aztec-nr/authwit" }
