[workspace]
members = [
    "crates/private-kernel-lib",
    "crates/private-kernel-init-lib",
    "crates/private-kernel-init",
    "crates/private-kernel-init-simulated",
    # "crates/private-kernel-ordering",
    # "crates/private-kernel-inner",
]
