[workspace]
members = [
    "contracts/account/ecdsa_k_account_contract",
    "contracts/account/ecdsa_r_account_contract",
    "contracts/account/schnorr_account_contract",
    "contracts/account/schnorr_hardcoded_account_contract",
    "contracts/account/schnorr_single_key_account_contract",
    "contracts/account/simulated_account_contract",
    "contracts/app/amm_contract",
    "contracts/app/app_subscription_contract",
    "contracts/app/auth_contract",
    "contracts/app/card_game_contract",
    "contracts/app/claim_contract",
    "contracts/app/crowdfunding_contract",
    "contracts/app/easy_private_token_contract",
    "contracts/app/easy_private_voting_contract",
    "contracts/app/escrow_contract",
    "contracts/app/lending_contract",
    "contracts/app/nft_contract",
    "contracts/app/orderbook_contract",
    "contracts/app/price_feed_contract",
    "contracts/app/token_blacklist_contract",
    "contracts/app/token_bridge_contract",
    "contracts/app/token_contract",
    "contracts/app/uniswap_contract",
    "contracts/app/simple_token_contract",
    "contracts/docs/docs_example_contract",
    "contracts/fees/fpc_contract",
    "contracts/fees/sponsored_fpc_contract",
    "contracts/protocol/auth_registry_contract",
    "contracts/protocol/contract_class_registry",
    "contracts/protocol/contract_instance_registry",
    "contracts/protocol/fee_juice_contract",
    "contracts/protocol/multi_call_entrypoint_contract",
    "contracts/protocol/router_contract",
    "contracts/test/auth_wit_test_contract",
    "contracts/test/avm_gadgets_test_contract",
    "contracts/test/avm_initializer_test_contract",
    "contracts/test/avm_test_contract",
    "contracts/test/benchmarking_contract",
    "contracts/test/child_contract",
    "contracts/test/counter_contract",
    "contracts/test/event_only_contract",
    "contracts/test/import_test_contract",
    "contracts/test/invalid_account_contract",
    "contracts/test/no_constructor_contract",
    "contracts/test/note_getter_contract",
    "contracts/test/offchain_effect_contract",
    "contracts/test/parent_contract",
    "contracts/test/pending_note_hashes_contract",
    "contracts/test/public_immutable_contract",
    "contracts/test/returning_tuple_contract",
    "contracts/test/spam_contract",
    "contracts/test/state_vars_contract",
    "contracts/test/stateful_test_contract",
    "contracts/test/static_child_contract",
    "contracts/test/static_parent_contract",
    "contracts/test/test_contract",
    "contracts/test/test_log_contract",
    "contracts/test/txe_test_contract",
    "contracts/test/updatable_contract",
    "contracts/test/updated_contract"
]
