version: '3'
services:
  ethereum:
    image: aztecprotocol/foundry:25f24e677a6a32a62512ad4f561995589ac2c7dc-${ARCH_TAG:-amd64}
    entrypoint: >
      sh -c '
      if [ -n "$$FORK_BLOCK_NUMBER" ] && [ -n "$$FORK_URL" ]; then
        exec anvil --silent -p "$$ANVIL_PORT" --host 0.0.0.0 --chain-id 31337 --fork-url "$$FORK_URL" --fork-block-number "$$FORK_BLOCK_NUMBER"
      else
        exec anvil --silent -p "$$ANVIL_PORT" --host 0.0.0.0 --chain-id 31337
      fi'
    ports:
      - '${ANVIL_PORT:-8545}:${ANVIL_PORT:-8545}'
    environment:
      FORK_URL:
      FORK_BLOCK_NUMBER:
      ANVIL_PORT: ${ANVIL_PORT:-8545}

  aztec:
    image: 'aztecprotocol/aztec:${SANDBOX_VERSION:-latest}'
    ports:
      - '${SANDBOX_PXE_PORT:-8080}:8080'
    environment:
      LOG_LEVEL: # Loaded from the user shell if explicitly set
      HOST_WORKDIR: '${PWD}' # Loaded from the user shell to show log files absolute path in host
      ETHEREUM_HOST: http://ethereum:8545
      L1_CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL_MS: 50
      P2P_BLOCK_CHECK_INTERVAL_MS: 50
      SEQ_TX_POLLING_INTERVAL_MS: 50
      WS_BLOCK_CHECK_INTERVAL_MS: 50
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log:rw
