name: Docs Preview

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  docs-preview:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Git
        run: |
          git config --global user.name AztecBot
          git config --global user.email tech@aztecprotocol.com

      - name: Generate directory hashes
        id: dir-hashes
        run: |
          echo "noir_hash=$(./noir/bootstrap.sh hash)" >> $GITHUB_OUTPUT
          echo "barretenberg_hash=$(./barretenberg/bootstrap.sh hash)" >> $GITHUB_OUTPUT
          echo "l1_contracts_hash=$(./l1-contracts/bootstrap.sh hash)" >> $GITHUB_OUTPUT
          echo "yarn_project_hash=$(./yarn-project/bootstrap.sh hash)" >> $GITHUB_OUTPUT

      - name: Restore Noir cache
        id: cache-noir
        uses: actions/cache@v4
        with:
          path: ./noir
          key: noir-build-${{ runner.os }}-${{ steps.dir-hashes.outputs.noir_hash }}
          restore-keys: |
            noir-build-${{ runner.os }}-

      - name: Restore Barretenberg cache
        id: cache-barretenberg
        uses: actions/cache@v4
        with:
          path: ./barretenberg
          key: barretenberg-build-${{ runner.os }}-${{ steps.dir-hashes.outputs.barretenberg_hash }}
          restore-keys: |
            barretenberg-build-${{ runner.os }}-

      - name: Restore L1 contracts cache
        id: cache-l1-contracts
        uses: actions/cache@v4
        with:
          path: ./l1-contracts
          key: l1-contracts-${{ runner.os }}-${{ steps.dir-hashes.outputs.l1_contracts_hash }}
          restore-keys: |
            l1-contracts-${{ runner.os }}-

      - name: Restore Yarn project cache
        id: cache-yarn-project
        uses: actions/cache@v4
        with:
          path: ./yarn-project
          key: yarn-project-${{ runner.os }}-${{ steps.dir-hashes.outputs.yarn_project_hash }}
          restore-keys: |
            yarn-project-${{ runner.os }}-

      - name: Build dependencies
        run: |
          if [[ "${{ steps.cache-noir.outputs.cache-hit }}" != 'true' ]]; then
            echo "Building Noir (cache miss)"
            ./noir/bootstrap.sh fast
          fi
          if [[ "${{ steps.cache-barretenberg.outputs.cache-hit }}" != 'true' ]]; then
            echo "Building Barretenberg (cache miss)"
            ./barretenberg/bootstrap.sh fast
          fi
          if [[ "${{ steps.cache-l1-contracts.outputs.cache-hit }}" != 'true' ]]; then
            echo "Building L1 contracts (cache miss)"
            ./l1-contracts/bootstrap.sh fast
          fi
          if [[ "${{ steps.cache-yarn-project.outputs.cache-hit }}" != 'true' ]]; then
            echo "Building Yarn project (cache miss)"
            ./yarn-project/bootstrap.sh fast
          fi

      - name: Run release-preview script
        working-directory: ./docs
        run: |
          echo "docs release preview"
          yarn install
          yarn build

          if ! deploy_output=$(yarn netlify deploy --site aztec-docs-dev 2>&1); then
            echo "Netlify deploy failed with error:"
            echo "$deploy_output"
            exit 1
          fi

          # Extract preview URL.
          docs_preview_url=$(echo "$deploy_output" | grep -E "https://.*aztec-docs-dev.netlify.app" | awk '{print $4}')
          if [ -z "$docs_preview_url" ]; then
            echo "Failed to extract preview URL from Netlify output."
          else
            echo "Docs preview URL: ${docs_preview_url}"
            echo "docs_preview_url=${docs_preview_url}" >> $GITHUB_ENV
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- AUTOGENERATED DOCS COMMENT -->"

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # Docs Preview
            You can check your [preview here](${{ env.docs_preview_url }}).

            <!-- AUTOGENERATED DOCS COMMENT -->
          edit-mode: replace

      - name: Reconfigure Git
        run: |
          git config --global user.name signorecello
          git config --global user.email outgoing@zkpedro.dev
