name: Docs Preview

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
    paths:
      - docs/**

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  docs-preview:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # The commit to checkout. We want our actual commit, and not the result of merging the PR to the target.
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          # Include previous commit for master history comparisons.
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: "22"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de
        with:
          version: nightly-99634144b6c9371982dcfc551a7975c5dbf9fad8

      - name: Configure Git
        run: |
          git config --global user.name AztecBot
          git config --global user.email tech@aztecprotocol.com

      - name: Build dependencies
        run: |
          export NOIR_HASH=$(./noir/bootstrap.sh hash)
          for project in noir barretenberg avm-transpiler noir-projects l1-contracts yarn-project; do
            $project/bootstrap.sh
          done

      # Making the bash script here so we don't accidentally deploy
      - name: Run release-preview script
        working-directory: ./docs
        run: |
          echo "docs release preview"
          yarn install
          yarn build

          if ! deploy_output=$(yarn netlify deploy --site aztec-docs-dev 2>&1); then
            echo "Netlify deploy failed with error:"
            echo "$deploy_output"
            exit 1
          fi

          # Extract preview URL.
          docs_preview_url=$(echo "$deploy_output" | grep -E "https://.*aztec-docs-dev.netlify.app" | awk '{print $4}')
          if [ -z "$docs_preview_url" ]; then
            echo "Failed to extract preview URL from Netlify output."
          else
            echo "Docs preview URL: ${docs_preview_url}"
            echo "docs_preview_url=${docs_preview_url}" >> $GITHUB_ENV
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1
        id: find-comment
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- AUTOGENERATED DOCS COMMENT -->"

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            # Docs Preview
            You can check your [preview here](${{ env.docs_preview_url }}).

            <!-- AUTOGENERATED DOCS COMMENT -->
          edit-mode: replace
