name: Publish Aztec Packages

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The tag to release"
        required: true
      publish:
        type: boolean
        description: "Whether to publish the release"
        required: true

permissions:
  # Necessary to upload new release artifacts
  contents: write
  issues: write

env:
  # Add any global environment variables here
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
  DEPLOY_TAG: ${{ github.event.inputs.tag }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag is valid
        id: check_tag
        run: |
          TAG=${{ github.event.inputs.tag }}
          if [[ "$TAG" == aztec-packages-v* ]]; then
            echo "Tag is valid. Proceeding with setup."
          else
            echo "Invalid tag format. Expected aztec-packages-v*"
            exit 1
          fi

  setup-x86:
    needs: check-version
    uses: ./.github/workflows/setup-runner.yml
    with:
      username: ${{ github.actor }}
      runner_type: builder-x86
    secrets: inherit

  setup-arm:
    needs: check-version
    uses: ./.github/workflows/setup-runner.yml
    with:
      username: ${{ github.actor }}
      runner_type: builder-arm
    secrets: inherit

  build-aztec-x86:
    needs: setup-x86
    runs-on: ${{ github.actor }}-x86
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.GIT_COMMIT }}"
      - uses: ./.github/ci-setup-action
        with:
          concurrency_key: build-aztec-${{ github.actor }}
          dockerhub_password: "${{ env.DOCKERHUB_PASSWORD }}"
      - name: Build & Push Aztec x86_64
        timeout-minutes: 40
        run: |
          earthly-ci \
            --no-output \
            --push \
            ./yarn-project+export-aztec-arch \
            --DIST_TAG=${{ env.GIT_COMMIT }} \
            --ARCH=x86_64

  build-aztec-arm:
    needs: setup-arm
    runs-on: ${{ github.actor }}-arm
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.GIT_COMMIT }}"
      - uses: ./.github/ci-setup-action
        with:
          concurrency_key: build-aztec-${{ github.actor }}
          dockerhub_password: "${{ env.DOCKERHUB_PASSWORD }}"
      - name: Build & Push Aztec arm64
        timeout-minutes: 60
        run: |
          earthly-ci \
            --no-output \
            --push \
            ./yarn-project+export-aztec-arch \
            --DIST_TAG=${{ env.GIT_COMMIT }} \
            --ARCH=arm64

  build-nargo-x86:
    needs: [setup-x86, build-aztec-x86]
    runs-on: ${{ github.actor }}-x86
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.GIT_COMMIT }}"
      - uses: ./.github/ci-setup-action
        with:
          concurrency_key: build-aztec-nargo-${{ github.actor }}
          dockerhub_password: "${{ env.DOCKERHUB_PASSWORD }}"

      - name: Build & push aztec nargo image
        run: |
          earthly-ci --no-output --push ./aztec-nargo+export-aztec-nargo --DIST_TAG=${{ env.GIT_COMMIT }} --ARCH=x86_64

  build-nargo-arm:
    needs: [setup-arm, build-aztec-arm]
    runs-on: ${{ github.actor }}-arm
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.GIT_COMMIT }}"
      - uses: ./.github/ci-setup-action
        with:
          concurrency_key: build-aztec-nargo-${{ github.actor }}
          dockerhub_password: "${{ env.DOCKERHUB_PASSWORD }}"

      - name: Build & push aztec nargo image
        run: |
          earthly-ci --no-output --push ./aztec-nargo+export-aztec-nargo --DIST_TAG=${{ env.GIT_COMMIT }} --ARCH=arm64

  build-cli-wallet-x86:
    needs: [setup-x86, build-aztec-x86]
    runs-on: ${{ github.actor }}-x86
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.GIT_COMMIT }}"
      - uses: ./.github/ci-setup-action
        with:
          concurrency_key: build-aztec-cli-wallet-${{ github.actor }}
          dockerhub_password: "${{ env.DOCKERHUB_PASSWORD }}"

      - name: Build & push aztec cli wallet image
        run: |
          earthly-ci --no-output --push ./yarn-project+export-cli-wallet --DIST_TAG=${{ env.GIT_COMMIT }} --ARCH=x86_64

  build-cli-wallet-arm:
    needs: [setup-arm, build-aztec-arm]
    runs-on: ${{ github.actor }}-arm
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.GIT_COMMIT }}"
      - uses: ./.github/ci-setup-action
        with:
          concurrency_key: build-aztec-cli-wallet-${{ github.actor }}
          dockerhub_password: "${{ env.DOCKERHUB_PASSWORD }}"

      - name: Build & push aztec cli wallet image
        run: |
          earthly-ci --no-output --push ./yarn-project+export-cli-wallet --DIST_TAG=${{ env.GIT_COMMIT }} --ARCH=arm64

  publish-manifests:
    needs:
      [
        build-aztec-x86,
        build-aztec-arm,
        build-nargo-x86,
        build-nargo-arm,
        build-cli-wallet-x86,
        build-cli-wallet-arm,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.GIT_COMMIT }}"
      - uses: ./.github/ci-setup-action
        with:
          dockerhub_password: "${{ env.DOCKERHUB_PASSWORD }}"
      - name: Publish aztec manifests
        if: ${{ github.event.inputs.publish }}
        run: |
          VERSION=${${{ env.DEPLOY_TAG }}#aztec-packages-v}

          docker pull aztecprotocol/aztec:${{ env.GIT_COMMIT }}-x86_64
          docker pull aztecprotocol/aztec:${{ env.GIT_COMMIT }}-arm64
          docker pull aztecprotocol/aztec-nargo:${{ env.GIT_COMMIT }}-x86_64
          docker pull aztecprotocol/aztec-nargo:${{ env.GIT_COMMIT }}-arm64
          docker pull aztecprotocol/cli-wallet:${{ env.GIT_COMMIT }}-x86_64
          docker pull aztecprotocol/cli-wallet:${{ env.GIT_COMMIT }}-arm64

          docker manifest create aztecprotocol/aztec:$VERSION \
            aztecprotocol/aztec:${{ env.GIT_COMMIT }}-x86_64 \
            aztecprotocol/aztec:${{ env.GIT_COMMIT }}-arm64
          docker manifest create aztecprotocol/aztec:latest \
            aztecprotocol/aztec:${{ env.GIT_COMMIT }}-x86_64 \
            aztecprotocol/aztec:${{ env.GIT_COMMIT }}-arm64
          docker manifest push aztecprotocol/aztec:$VERSION
          docker manifest push aztecprotocol/aztec:latest

          docker manifest create aztecprotocol/aztec-nargo:$VERSION \
            aztecprotocol/aztec-nargo:${{ env.GIT_COMMIT }}-x86_64 \
            aztecprotocol/aztec-nargo:${{ env.GIT_COMMIT }}-arm64
          docker manifest create aztecprotocol/aztec-nargo:latest \
            aztecprotocol/aztec-nargo:${{ env.GIT_COMMIT }}-x86_64 \
            aztecprotocol/aztec-nargo:${{ env.GIT_COMMIT }}-arm64
          docker manifest push aztecprotocol/aztec-nargo:$VERSION
          docker manifest push aztecprotocol/aztec-nargo:latest

          docker manifest create aztecprotocol/cli-wallet:$VERSION \
            aztecprotocol/cli-wallet:${{ env.GIT_COMMIT }}-x86_64 \
            aztecprotocol/cli-wallet:${{ env.GIT_COMMIT }}-arm64
          docker manifest create aztecprotocol/cli-wallet:latest \
            aztecprotocol/cli-wallet:${{ env.GIT_COMMIT }}-x86_64 \
            aztecprotocol/cli-wallet:${{ env.GIT_COMMIT }}-arm64
          docker manifest push aztecprotocol/cli-wallet:$VERSION
          docker manifest push aztecprotocol/cli-wallet:latest

  publish-npm:
    needs: publish-manifests
    runs-on: ${{ github.actor }}-x86
    if: ${{ github.event.inputs.publish }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_COMMIT }}

      - name: Publish yarn-project NPM packages
        run: |
          VERSION=${${{ env.DEPLOY_TAG }}#aztec-packages-v}
          earthly-ci \
            --no-output \
            --secret NPM_TOKEN=${{ env.NPM_TOKEN }} \
            ./yarn-project+publish-npm \
            --DIST_TAG=latest \
            --VERSION=$VERSION
            --DRY_RUN=${{ (github.event.inputs.publish == 'false') && '1' || '0' }}

      - name: Publish bb.js NPM package
        run: |
          VERSION=${${{ env.DEPLOY_TAG }}#aztec-packages-v}
          earthly-ci \
            --no-output \
            --secret NPM_TOKEN=${{ env.NPM_TOKEN }} \
            ./barretenberg/ts+publish-npm \
            --DIST_TAG=latest \
            --VERSION=$VERSION
            --DRY_RUN=${{ (github.event.inputs.publish == 'false') && '1' || '0' }}
