name: Reindex TypeSense

on:
# testing
 push:
    branches:
      - docs/typesense-reindex-in-ci
  # release:
  #   types: [prereleased, published]
jobs:
  reindex:
    name: Reindex docs in TypeSense
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Reindex with docsearch-scraper
        run: |
          docker run \
            -e "TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY }}" \
            -e "TYPESENSE_HOST=${{ secrets.TYPESENSE_HOST }}" \
            -e "TYPESENSE_PORT=443" \
            -e "TYPESENSE_PROTOCOL=https" \
            -e "CONFIG=$(cat docs/typesense.config.json | jq -r tostring)" \
            typesense/docsearch-scraper:0.11.0
