# Useful if the publish npm runner is in a bad state
name: Start Legacy Runner
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
      runner_type:
        description: 'Runner type (optional)'
        default: builder-x86
        required: true
jobs:
  start-build:
    uses: ./.github/workflows/setup-runner.yml
    with:
      username: ${{ inputs.username }}
      runner_type: ${{ inputs.runner_type }}
    secrets: inherit
