name: AVM Full Tests

on:
  schedule:
    - cron: "15 4 * * 1-5" # Monday to Friday at 4:15 AM UTC
  workflow_dispatch:
    inputs: {}

concurrency:
  # force parallelism in master
  group: avm-full-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # barretenberg (prover) native and AVM (public VM) tests
  # only ran on x86 for resource reasons (memory intensive)
  avm-full-tests:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
      RUN_ID: ${{ github.run_id }}
      RUN_ATTEMPT: ${{ github.run_attempt }}
      GITHUB_TOKEN: ${{ github.token }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUILD_INSTANCE_SSH_KEY: ${{ secrets.BUILD_INSTANCE_SSH_KEY }}
      GITHUB_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}"
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with: { ref: "${{ env.GIT_COMMIT }}" }
      - name: "AVM Full Tests"
        uses: ./.github/ensure-tester
        timeout-minutes: 75
        with:
          run: |
            sudo shutdown -P 75 # hack until core part of the scripts
            earthly-ci --no-output ./barretenberg/cpp/+vm-full-test --hardware_concurrency=64  # limit our parallelism to half our cores
